### ISSUE TITLE
Contrast of Cursor with Background of My Theme

### ISSUE THREAD

**Issue by jameswomack** [wincent/terminus#2]
Hello @wincent — thank you for releasing this valuable plug for Vim.

AFAIK there isn't a config var for changing the cursor color. In my theme, it appears black on black. Is there something I can change at https://github.com/wincent/terminus/blob/b474da203eca78e551d67e79abdf2f1e9a6b48dc/plugin/terminus.vim#L29 to remedy this?

<img width="366" alt="screen shot 2015-07-07 at 12 00 17 pm" src="https://cloud.githubusercontent.com/assets/77849/8554658/cf301982-249f-11e5-9a30-998c6b74c908.png">

**Comment by wincent** [comment]
Here's what it looks like for me (normal mode):

![Normal mode cursor](https://www.evernote.com/shard/s219/sh/4faa9509-77ab-4f2f-a265-b430bb6176a0/cc1ff112f832ce09/res/2338bb86-e004-4c44-81cc-31d42fe1f416/skitch.png)

And insert mode:

![Insert mode cursor](https://www.evernote.com/shard/s219/sh/e3e6ae2a-3f0b-40ec-9bbb-2ac6c7b3f7ea/cf8147cb13c7b403/res/6e46dc01-1146-449b-88c5-56adc41149c4/skitch.png)

You'll notice the cursor color doesn't actually change, and it's a very narrow (1-pixel?) strip in insert mode. I don't think you'd be able to change either of those aspects of it without hacking iTerm.

FWIW, I've recently cleaned up and made things more minimalist (specifically relevant here, I turn off `'cursorline'` when in insert mode, and I'm not using `'cursorcolumn'` any more, since I was mostly only using it to get more visible search results, and you can get those with [Loupe](https://github.com/wincent/loupe) instead), and that helps with visibility.

I don't think there's much I can do here, other than add an entry to the docs explaining the limitation and offering some possible suggestions.

**Comment by wincent** [comment]
I've added a tip to the `TROUBLESHOOTING` section to address this, so I'm going to close. Thanks for opening the issue!

**Comment by jameswomack** [comment]
Thank you
